webapp/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
import datetime


views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    from .models import Tracker
    from . import db
    user = current_user.id
    from .models import Tracker, Log
    tracker = db.session.query(Tracker).with_entities(
        Tracker.name, Tracker.id, Tracker.description).distinct().filter(Tracker.uid == user).all()
    logs = db.session.query(Log).with_entities(
        Log.id).distinct().filter(Log.uid == user).all()
    print(tracker)

    return render_template("home.html", user=current_user, tracker=tracker, tracker_count=len(tracker), log_count=len(logs))


@views.route('/add-tracker', methods=['GET', 'POST'])
@login_required
def add_tracker():
    if request.method == "GET":
        from . import db
        from .models import Tracker
        user = current_user.id
        tracker = db.session.query(Tracker).with_entities(
            Tracker.name, Tracker.id, Tracker.description).distinct().filter(Tracker.uid == user).all()
        return render_template("addtracker.html", user=current_user, tracker=tracker, tracker_count=len(tracker))
    if request.method == 'POST':
        name = request.form['name']
        type = request.form['Action']
        settings = request.form['settings']
        description = request.form['description']

        from .models import Tracker

        tracker = Tracker.query.filter_by(name=name).first()
        user = current_user.id

        if tracker and user == tracker.uid:
            flash('The tracker "' + name + '" already exists', category='error')
            return redirect(url_for('views.add_tracker'))
        else:
            from . import db
            tracker_info = Tracker(
                name=name, description=description, type=type, settings=settings, uid=user)
            db.session.add(tracker_info)
            db.session.commit()
            flash(name + ' Tracker Added', category='success')
            return redirect(url_for('views.home'))


@views.route('/delete-tracker/<int:tid>', methods=['GET', 'POST'])
@login_required
def delete_tracker(tid):
    from .models import Tracker
    tracker = Tracker.query.get(tid)
    from . import db
    db.session.delete(tracker)
    db.session.commit()
    flash(tracker.name + ' Tracker Removed Successfully.', category='success')
    return redirect(url_for('views.home'))


@views.route("/trackerinfo/<int:tid>", methods=["GET", "POST"])
@login_required
def trinfo(tid):
    if request.method == "GET":
        from .models import Tracker, Log
        logs = Log.query.filter(Log.tid == tid).all()
        tracker = Tracker.query.with_entities(
            Tracker.type, Tracker.name).filter(Tracker.id == tid).first()

        return render_template("trackerinfo.html", tracker=tracker, user=current_user, logs=logs, tid=tid)


@views.route('/edit-tracker/<int:tid>', methods=['GET', 'POST'])
@login_required
def edit_tracker(tid):
    user = current_user.id
    from .models import Tracker
    tracker = Tracker.query.get(tid)

    from . import db
    trackers = db.session.query(Tracker).with_entities(
        Tracker.name, Tracker.id, Tracker.description).distinct().filter(Tracker.uid == user).all()
    if request.method == "GET":
        return render_template("edittracker.html", user=current_user, tracker=tracker, tid=tid, trackers=trackers)

    if request.method == 'POST':
        type = request.form['Action']
        settings = request.form['settings']
        description = request.form['description']
        uid = current_user.id
        from . import db
        tracker.description = description
        tracker.type = type
        tracker.settings = settings
        db.session.commit()
        flash('Tracker Updated Successfully.', category='success')
        return redirect(url_for('views.home'))


@views.route('/add-log/<int:tid>', methods=['GET', 'POST'])
@login_required
def add_log(tid):
    from .models import Tracker, Log
    user = current_user.id
    tracker = Tracker.query.get(tid)
    logs = Log.query.filter(Log.tid == tid).all()
    import datetime
    now = datetime.datetime.now()
    options = []
    from . import db
    trackers = db.session.query(Tracker).with_entities(
        Tracker.name, Tracker.id, Tracker.description).distinct().filter(Tracker.uid == user).all()
    if tracker.type == "multiple_choice":
        option = tracker.settings
        options = option.split(',')

    if request.method == "GET":
        return render_template("addlog.html", user=current_user, tracker=tracker, now=now, tid=tid, options=options, trackers=trackers, logs=logs)

    if request.method == 'POST':
        when = request.form['date']
        value = request.form['value']
        note = request.form['note']
        from . import db
        log_info = Log(timestamp=when, value=value, note=note,
                       tid=tid, uid=current_user.id, added_date_time=now)
        db.session.add(log_info)
        db.session.commit()
        flash('New Log Added For ' + tracker.name +
              ' Tracker', category='success')
        return redirect(url_for('views.trinfo', tid=tid))


@views.route('/edit-log/<int:lid>', methods=['GET', 'POST'])
@login_required
def edit_log(lid):
    from .models import Log, Tracker
    from . import db
    options = []
    from . import db
    logs = Log.query.get(lid)
    all_logs = Log.query.filter(Log.tid == logs.tid).all()
    tracker = Tracker.query.get(logs.tid)
    user = current_user.id
    
    if tracker.type == "multiple_choice":
        option = tracker.settings
        options = option.split(',')

    if request.method == 'POST':
        when = request.form.get('date')
        value = request.form.get('value')
        note = request.form.get('note')


        logs.timestamp = when
        logs.value = value
        logs.note = note

        db.session.commit()

        return redirect(url_for('views.trinfo', tid=logs.tid))
    return render_template("editlog.html", user=current_user, tracker=tracker, log=logs, tid=logs.tid, all_logs=all_logs, options=options)


@views.route('/delete-log/<int:lid>', methods=['GET', 'POST'])
@login_required
def delete_log(lid):
    from .models import Log
    loginfo = Log.query.get(lid)
    tid = loginfo.tid
    from . import db
    db.session.delete(loginfo)
    db.session.commit()
    return redirect(url_for('views.trinfo', tid=tid))

webapp/templates/addlog.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/70209db3cd.js" crossorigin="anonymous"></script>

    <title>Home</title>
</head>

<body>
    <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <div class="container_home">
        <nav class="navbar_home">
            <div class="navbar__left">
                <a href="/trackerinfo/{{tid}}">View Tracker</a>
                <a href="/add-log/{{tid}}" class="active_link">Add Logs</a>
                <a href="/edit-tracker/{{tid}}">Edit Tracker</a>
                <a href="{{ url_for('views.delete_tracker', tid = tid) }}">Delete Tracker</a>
            </div>
            <div class="navbar__right">
                <a href="#">{{user.email}}</a>
                <a href="#">
                    <i class="fa-solid fa-user"></i>
                </a>
            </div>
        </nav>


        <main>
            <div class="main__container">
                <!-- MAIN TITLE STARTS HERE -->

                <div class="main__title" style="margin-top: 10px;">
                    <div class="main__greeting">
                        <h1>Add a log to {{tracker['name']}}</h1>
                    </div>
                </div>


                <div class="grid">
                    <form method="post">
                        <h3>Log Information</h3>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}

                        {% for category, message in messages %}

                        {% if category == 'error' %}
                        <div align="center">
                            <div class="error" role="alert">
                                {{ message }}
                            </div>

                        </div>
                        {% else %}
                        <div align="center">
                            <div class="success" role="alert">
                                {{ message }}
                            </div>
                        </div>
                        {% endif %}

                        {% endfor %}

                        {% endif %}
                        {% endwith %}
                        <label for="date">Date</label>
                        <input type="date" name="date" required>
                        <label for="value">Value</label>
                        {% if tracker['type']=='numerical' %}
                        <input type="number" id="value" name="value"
                            placeholder="Enter Number" maxlength="30"
                            required />
                        {% elif tracker['type']=='multiple_choice' %}
                        <select id="value" name="value" required>
                            {% for element in options %}
                            <option value={{element}}>{{element}}</option>
                            {% endfor %}
                        </select>
                        {% endif %}
                        <label for="note">Note</label>
                        <input type="note" placeholder="Note" name="note"><br><br>
                        <input type="submit" value="Submit" class="bttn glow-bttn">
                        </p>
                    </form>

                    <!-- End of Error and Success Message-->

                    <div class="grid__right">
                        <div class="grid__right__title">
                            <div style="width: 100%;">
                                <h1>{{tracker['name']}} Logs</h1>
                                <p>Check and edit your logs</p>
                            </div>
                            </div>
                            <table class="table text-light">
                                <thead>
                                    <tr>
                                        <th scope="col">On</th>
                                        <th scope="col">Value</th>
                                        <th scope="col">Note</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for i in logs %}
                                    <tr>
                    
                                        <td>{{i['timestamp']}}</td>
                                        <td>{{i['value']}}</td>
                                        <td>{{i['note']}}</td>
                                        <td><a href="/edit-log/{{i['id']}}" style="margin-right: 5px; color:darksalmon">Edit</a>||<a href="/delete-log/{{i['id']}}" style="margin-left: 5px; color:darksalmon">Delete</a></td>
                                    {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
        </main>


        <div id="sidebar">
            <div class="sidebar__title">
                <div class="sidebar__img">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
                </div>
                <i onclick="closeSidebar()" class="fa fa-times" id="sidebarIcon" aria-hidden="true"></i>
            </div>

            <div class="sidebar__menu">
                <div class="sidebar__link">
                    <i class="fa fa-home"></i>
                    <a href="/">Dashboard</a>
                </div>

                <div class="sidebar__logout">
                    <i class="fa fa-power-off"></i>
                    <a href="/">Log out</a>
                </div>
            </div>

        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/editlog.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/70209db3cd.js" crossorigin="anonymous"></script>

    <title>Home</title>
</head>

<body>
    <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <div class="container_home">
        <nav class="navbar_home">
            <div class="navbar__left">
                <a href="/trackerinfo/{{tid}}">View Tracker</a>
                <a href="#">Add Logs</a>
                <a href="/edit-tracker" class="active_link">Edit Tracker</a>
                <a href="{{ url_for('views.delete_tracker', tid = tid) }}">Delete Tracker</a>
            </div>
            <div class="navbar__right">
                <a href="#">{{user.email}}</a>
                <a href="#">
                    <i class="fa-solid fa-user"></i>
                </a>
            </div>
        </nav>


        <main>
            <div class="main__container">
                <!-- MAIN TITLE STARTS HERE -->

                <div class="main__title" style="margin-top: 10px;">
                    <div class="main__greeting">
                        <h1>Edit Tracker {{tracker['name']}}</h1>
                    </div>
                </div>


                <div class="grid">
                    <form method="post">
                        <h3>Update Log</h3>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}

                        {% for category, message in messages %}

                        {% if category == 'error' %}
                        <div align="center">
                            <div class="error" role="alert">
                                {{ message }}
                            </div>

                        </div>
                        {% else %}
                        <div align="center">
                            <div class="success" role="alert">
                                {{ message }}
                            </div>
                        </div>
                        {% endif %}

                        {% endfor %}

                        {% endif %}
                        {% endwith %}
                        <label for="date">Date</label>
                        <input type="date" name="date" required>
                        <label for="value">Value</label>
                        {% if tracker['type']=='numerical' %}
                        <input type="number" id="value" name="value"
                            placeholder="Enter Number" maxlength="30"
                            required />
                        {% elif tracker['type']=='multiple_choice' %}
                        <select id="value" name="value" required>
                            {% for element in options %}
                            <option value={{element}}>{{element}}</option>
                            {% endfor %}
                        </select>
                        {% endif %}
                        <label for="note">Note</label>
                        <input type="note" placeholder="Note" name="note"><br><br>
                        <input type="submit" value="Submit" class="bttn glow-bttn">
                        </p>
                    </form>

                    <!-- End of Error and Success Message-->

                    <div class="grid__right">
                        <div class="grid__right__title">
                            <div style="width: 100%;">
                                <h1>{{tracker['name']}} Logs</h1>
                                <p>Check logs</p>
                            </div>
                            </div>
                            <table class="table text-light">
                                <thead>
                                    <tr>
                                        <th scope="col">On</th>
                                        <th scope="col">Value</th>
                                        <th scope="col">Note</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for i in all_logs %}
                                    <tr>
                    
                                        <td>{{i['timestamp']}}</td>
                                        <td>{{i['value']}}</td>
                                        <td>{{i['note']}}</td>
                                        <td><a href="/edit-log/{{i['id']}}" style="margin-right: 5px; color:darksalmon">Edit</a>||<a href="/delete-log/{{i['id']}}" style="margin-left: 5px; color:darksalmon">Delete</a></td>
                                    {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
        </main>


        <div id="sidebar">
            <div class="sidebar__title">
                <div class="sidebar__img">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
                </div>
                <i onclick="closeSidebar()" class="fa fa-times" id="sidebarIcon" aria-hidden="true"></i>
            </div>

            <div class="sidebar__menu">
                <div class="sidebar__link">
                    <i class="fa fa-home"></i>
                    <a href="/">Dashboard</a>
                </div>

                <div class="sidebar__logout">
                    <i class="fa fa-power-off"></i>
                    <a href="/">Log out</a>
                </div>
            </div>

        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/edittracker.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/70209db3cd.js" crossorigin="anonymous"></script>

    <title>Home</title>
</head>

<body>
    <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <div class="container_home">
        <nav class="navbar_home">
            <div class="navbar__left">
                <a href="/trackerinfo/{{tid}}">View Tracker</a>
                <a href="/add-log/{{tid}}">Add Logs</a>
                <a href="/edit-tracker" class="active_link">Edit Tracker</a>
                <a href="{{ url_for('views.delete_tracker', tid = tid) }}">Delete Tracker</a>
            </div>
            <div class="navbar__right">
                <a href="#">{{user.email}}</a>
                <a href="#">
                    <i class="fa-solid fa-user"></i>
                </a>
            </div>
        </nav>


        <main>
            <div class="main__container">
                <!-- MAIN TITLE STARTS HERE -->

                <div class="main__title" style="margin-top: 10px;">
                    <div class="main__greeting">
                        <h1>Edit Tracker {{tracker['name']}}</h1>
                    </div>
                </div>


                <div class="grid">
                    <form method="post">
                        <h3>Update Tracker Information</h3>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}

                        {% for category, message in messages %}

                        {% if category == 'error' %}
                        <div align="center">
                            <div class="error" role="alert">
                                {{ message }}
                            </div>

                        </div>
                        {% else %}
                        <div align="center">
                            <div class="success" role="alert">
                                {{ message }}
                            </div>
                        </div>
                        {% endif %}

                        {% endfor %}

                        {% endif %}
                        {% endwith %}
                        <label for="description">Description</label>
                        <input type="description" placeholder="Describe your Tracker" name="description">
                        <label for="type">Type</label>
                        <select name="Action" id="action">
                            <option value="numerical">Numerical</option>
                            <option value="multiple_choice">Multiple Choice</option>
                        </select>
                        <label for="settings">Settings</label>
                        <input type="settings" placeholder="Only for Multiple Choice Type" name="settings"><br><br>
                        <input type="submit" value="Submit" class="bttn glow-bttn">
                        </p>
                    </form>

                    <!-- End of Error and Success Message-->

                    <div class="grid__right">
                        <div class="grid__right__title">
                            <div style="width: 100%;">
                                <h1>Your Current Trackers</h1>
                                <p>Check or Edit your Trackers</p>
                            </div>
                        </div>
                        {% if tracker_count == 0 %}
                        <div class="message" role="alert">
                            Looks like, there is nothing here!
                        </div>
                        {% else %}
                        <div class="trackers__cards__long">
                            {% for i in trackers %}
                            <a href="#" class="tracker">
                                <h1>{{i["name"]}}</h1>
                                <p>{{i["description"]}}</p>
                            </a>
                            {% endfor %}
                            {% endif %}
                        </div>
        </main>


        <div id="sidebar">
            <div class="sidebar__title">
                <div class="sidebar__img">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
                </div>
                <i onclick="closeSidebar()" class="fa fa-times" id="sidebarIcon" aria-hidden="true"></i>
            </div>

            <div class="sidebar__menu">
                <div class="sidebar__link">
                    <i class="fa fa-home"></i>
                    <a href="/">Dashboard</a>
                </div>

                <div class="sidebar__logout">
                    <i class="fa fa-power-off"></i>
                    <a href="/">Log out</a>
                </div>
            </div>

        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/trackerinfo.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/70209db3cd.js" crossorigin="anonymous"></script>

    <title>Home</title>
</head>

<body>
    <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <div class="container_home">
        <nav class="navbar_home">
            <div class="navbar__left">
                <a class="active_link">View Tracker</a>
                <a href="/add-log/{{tid}}">Add Logs</a>
                <a href="/edit-tracker/{{tid}}">Edit Tracker</a>
                <a href="{{ url_for('views.delete_tracker', tid = tid) }}">Delete Tracker</a>
            </div>
            <div class="navbar__right">
                <a href="#">{{user.email}}</a>
                <a href="#">
                    <i class="fa-solid fa-user"></i>
                </a>
            </div>
        </nav>


        <main>
            <div class="main__container">
                <!-- MAIN TITLE STARTS HERE -->

                <div class="main__title" style="margin-top: 10px;">
                    <div class="main__greeting">
                        <h1>{{tracker['name']}} Tracker</h1>
                    </div>
                </div>


                <div class="grid">
                    <div class="grid__left">
                        <div class="grid__left__title">
                            <div style="width: 100%;">
                                <h1>{{tracker['name']}} Logs</h1>
                                <p>Check and Edit your Logs</p>
                            </div>
                            </div>
                            <table class="table text-light">
                                <thead>
                                    <tr>
                                        <th scope="col">On</th>
                                        <th scope="col">Value</th>
                                        <th scope="col">Note</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for i in logs %}
                                    <tr>
                    
                                        <td>{{i['timestamp']}}</td>
                                        <td>{{i['value']}}</td>
                                        <td>{{i['note']}}</td>
                                        <td><a href="/edit-log/{{i['id']}}" style="margin-right: 5px; color:darksalmon">Edit</a>||<a href="/delete-log/{{i['id']}}" style="margin-left: 5px; color:darksalmon">Delete</a></td>
                                    {% endfor %}
                                    </tr>
                                </tbody>
                            </table>

                    </div>



                    <div class="grid__right">
                        <div class="grid__right__title"></div>
                    </div>
        </main>


        <div id="sidebar">
            <div class="sidebar__title">
                <div class="sidebar__img">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
                </div>
                <i onclick="closeSidebar()" class="fa fa-times" id="sidebarIcon" aria-hidden="true"></i>
            </div>

            <div class="sidebar__menu">
                <div class="sidebar__link">
                    <i class="fa fa-home"></i>
                    <a href="/">Dashboard</a>
                </div>

                <div class="sidebar__logout">
                    <i class="fa fa-power-off"></i>
                    <a href="/">Log out</a>
                </div>
            </div>

        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>